export const LOADING_ADMIN= "LOADING_ADMIN";
export const LOADING_PROF = "LOADING_PROF";
export const LOADING_PARENT = "LOADING_PARENT";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const SIGNUP_ADMIN_SUCCESS = "SIGNUP_ADMIN_SUCCESS";
export const SIGNUP_ADMIN_FAIL = "SIGNUP_ADMIN_FAIL";
export const SIGNUP_PROF_SUCCESS = "SIGNUP_PROF_SUCCESS";
export const SIGNUP_PROF_FAIL = "SIGNUP_PROF_FAIL";
export const SIGNUP_PARENT_SUCCESS = "SIGNUP_PARENT_SUCCESS";
export const SIGNUP_PARENT_FAIL = "SIGNUP_PARENT_FAIL";
export const SIGNUP_ELEVE_SUCCESS = "SIGNUP_ELEVE_SUCCESS";
export const SIGNUP_ELEVE_FAIL = "SIGNUP_ELEVE_FAIL";



export const LOGOUT_USER = "LOGOUT_USER";
export const CURRENT_USER = "CURRENT_USER";
export const CURRENT_FAIL = "CURRENT_FAIL";
