export const LOADING_REGISTRE = "LOADING_REGISTRE";
export const GET_REGISTRE_SUCCESS = "GET_REGISTRE_SUCCESS";
export const GET_REGISTRE_FAIL = "GET_REGISTRE_FAIL";

export const PUT_ABSENCE_SUCCESS = "PUT_ABSENCE_SUCCESS";
export const PUT_ABSENCE_FAIL = "PUT_ABSENCE_FAIL";